VER_INDEX = 0;
MUSIC_INDEX = 1;
NAME_IMDEX = 2;
ID_INDEX = 3;
DISP_INDEX = 4;
DIFF_INDEX = 5; 

music_table = [
    [2,1, "RUGGED ASH†", "rugged_l", "RUG", "A"],
    [3,2, "era(nostalmix)(H)", "eranos", "era(n H", "H"],
    [3,3, "era(nostalmix)(A)", "eranos", "era(n A", "A"],
    [3,4, "Holic", "holic", "Holi", "A"],
    [4,5, "DXY!(H)", "dxy", "DXY H", "H"],
    [4,6, "DXY!(A)", "dxy", "DXY A", "A"],
    [4,7, "era(step mix)", "erastep", "era(s", "A"],
    [4,8, "minimalian", "mnmlian", "mini", "A"],
    [4,9, "starmine", "starmine", "star", "A"],
    [4,10, "SWEET LAB", "swtlab24", "SWEET", "A"],
    [5,11, "QQQ", "qqq", "QQQ", "A"],
    [6,12, "Colors(radio edit)", "colors", "Colors", "A"],
    [6,13, "G2", "g2", "G2", "A"],
    [6,14, "NEMESIS", "nemesis", "NEME", "A"],
    [6,15, "route 80s", "r80s_emp", "80s", "A"],
    [6,16, "Summer Vacation(CU mix)", "summer", "Summ V", "A"],
    [7,17, "A", "a_amuro", "A", "A"],
    [7,18, "Cheer Train", "cheertra", "Cheer", "A"],
    [7,19, "Spica", "spica", "Spica", "A"],
    [7,20, "stoic", "stoic", "Stoic", "A"],
    [7,21, "革命(H)", "_kakumei", "革命H", "H"],
    [7,22, "革命(A)", "_kakumei", "革命A", "A"],
    [8,23, "murmur twins", "murmur", "murmur", "A"],
    [8,24, "桜", "_sakura", "桜", "A"],
    [9,25, "Karma", "karma", "Karma", "A"],
    [9,26, "lower world", "loworld", "lower", "A"],
    [9,27, "moon_child", "m_child", "moon", "A"],
    [9,28, "quasar", "quasar", "quasar", "A"],
    [9,29, "RISLIM-Remix-", "rislimr", "RISLIM", "A"],
    [10,30, "GHOST REVIVAL", "ghost", "GHOST", "A"],
    [10,31, "Innocent Walls", "innocent", "Walls", "A"],
    [10,32, "Love Is Eternity", "loveter", "LisE", "A"],
    [10,33, "No.13", "no13", "No.13", "A"],
    [10,34, "One More Lovely", "onemore", "OML", "A"],
    [10,35, "1st Samurai", "1samurai", "1st", "A"],
    [10,36, "雪月花", "_stgekka", "雪月花", "A"],
    [11,37, "AA", "aa_amuro", "AA", "A"],
    [11,38, "BLOCKS", "blocks", "BLOCKS", "A"],
    [11,39, "FAKE TIME(H)", "faketime", "FAKE H", "H"],
    [11,40, "FAKE TIME(A)", "faketime", "FAKE A", "A"],
    [11,41, "GENOCIDE(H)", "genocide", "GENO H", "H"],
    [11,42, "GENOCIDE(A)", "genocide", "GENO A", "A"],
    [11,43, "gigadelic(H)", "gigadel", "giga H", "H"],
    [11,44, "gigadelic(A)", "gigadel", "giga A", "A"],
    [11,45, "RED ZONE†", "redzonel", "RED Z", "A"],
    [11,46, "Sphere", "sphere", "Sphere", "A"],
    [11,47, "spiral galaxy†", "spiral_l", "spiral", "A"],
    [11,48, "ピアノ協奏曲第１番 蠍火", "_psasori", "蠍火", "A"],
    [12,49, "garden", "gardenhs", "garden", "A"],
    [12,50, "INAZUMA", "inazuma", "INAZUMA", "A"],
    [12,51, "Little Little Princess†", "littlepl", "LLP†", "A"],
    [12,52, "SCREAM SQUAD", "sc_squad", "SC SQ", "A"],
    [12,53, "冥", "_mei", "冥", "A"],
    [13,54, "Concertino in Blue", "concert", "Concer", "A"],
    [13,55, "CONTRACT", "contract", "CONTRA", "A"],
    [13,56, "CONTRACT†", "contracl", "CONTRA†", "A"],
    [13,57, "DUE TOMORROW", "due_tmrw", "DUE", "A"],
    [13,58, "Ganymede", "ganymede", "Gany", "A"],
    [13,59, "MINT", "mint", "MINT", "A"],
    [13,60, "tripping contact(teranoid&MC Natsack Remix)", "trip_mc", "trip", "A"],
    [13,61, "waxing and wanding†", "waxing_l", "wax", "A"],
    [13,62, "華蝶風雪", "_kachofu", "華蝶風雪", "A"],
    [13,63, "カゴノトリ～弐式～", "_kagono", "カゴ", "A"],
    [13,64, "嘆きの樹", "_nageki", "嘆き", "A"],
    [14,65, "Candy Galy", "candygal", "Candy", "A"],
    [14,66, "Fascination MAXX", "fas_maxx", "FaXX", "A"],
    [14,67, "INORI", "inori", "INORI", "A"],
    [14,68, "KAMAITACHI", "kmitachi", "KAMA", "A"],
    [14,69, "KAMAITACHI†", "kmitachl", "KAMA †", "A"],
    [14,70, "LASER CRUSTER", "lcruster", "LASER", "A"],
    [14,71, "op.31 叙情", "op31jojo", "op.31", "A"],
    [14,72, "Sense 2007(H)", "sens2007", "SenseH", "H"],
    [14,73, "Sense 2007(A)", "sens2007", "SenseA", "A"],
    [14,74, "smile", "smile", "smile", "A"],
    [14,75, "snow storm", "snwstorm", "snow", "A"],
    [14,76, "TRANOID", "tranoid", "TRANO", "A"],
    [14,77, "VANESSA", "vanessa", "VANE ", "A"],
    [14,78, "VANESSA†", "vanessal", "VANE †", "A"],
    [14,79, "電人、暁に斃れる。", "_fattack", "暁", "A"],
    [15,80, "Anisakis-somatic mutation type Forza", "anisakis", "Anisakis", "A"],
    [15,81, "Be OK", "be_ok", "BeOK", "A"],
    [15,82, "Blue Rain†", "bluerail", "Blue †", "A"],
    [15,83, "Do it!! Do it!!", "doit_emp", "Do it", "A"],
    [15,84, "four pieces of heaven", "fourpces", "four", "A"],
    [15,85, "ICARUS", "icarus", "ICA", "A"],
    [15,86, "ICARUS†", "icarusl", "ICA †", "A"],
    [15,87, "MENDES", "mendes", "MENDES", "A"],
    [15,88, "oratio", "oratio", "oratio", "A"],
    [15,89, "PARANOiA ～HADES～", "pr_hades", "P HADES", "A"],
    [15,90, "satellite020712 from CODED ARMS", "sa2712ac", "sate", "A"],
    [15,91, "State Of The Art", "sotart24", "State", "A"],
    [15,92, "THE DEEP STRIKER†", "tdeepstl", "DEEP †", "A"],
    [15,93, "TROOPERS", "troopers", "TROOPE", "A"],
    [15,94, "Ubertreffen†", "ubertrel", "Uber†", "A"],
    [15,95, "少年A", "_kid_a", "少年A", "A"],
    [15,96, "ミラージュレジデンス", "_m_resid", "ミラージュ", "A"],
    [16,97, "Colorful Cookie", "cocookie", "Cookie", "A"],
    [16,98, "Go Beyond!!", "gobeyond", "Beyond", "A"],
    [16,99, "Kung-fu Empire†", "kungfu_l", "Empire†", "A"],
    [16,100, "Y&Co. is dead or alive", "ycodoa25", "Y&Co", "A"],
    [16,101, "3y3s", "3y3s", "3y3s", "A"],
    [16,102, "卑弥呼", "_himiko", "卑弥呼", "A"],
    [16,103, "ミッドナイト堕天使", "_mdatn24", "堕天使", "A"],
    [16,104, "凛として咲く花の如く†", "_rintosl", "凛†", "A"],
    [17,105, "Almagest", "almag_ra", "Almag", "A"],
    [17,106, "Bad Maniacs", "bmaniacs", "Bad", "A"],
    [17,107, "DOMINION", "dominion", "DOMI", "A"],
    [17,108, "eRAseRmOToRpHAntOM", "ephantom", "sRaseR", "A"],
    [17,109, "Evans", "evans", "Evans", "A"],
    [17,110, "EXUSIA", "exusia", "EXUSIA", "A"],
    [17,111, "G59", "g59", "G59", "A"],
    [17,112, "GALGALIM", "galgalim", "GALGAL", "A"],
    [17,113, "GOLDEN CROSS", "goldcros", "GOLCRO", "A"],
    [17,114, "quell～the seventh slave～", "quell", "quell", "A"],
    [17,115, "Raison d'etre～交差する宿命～", "raison", "Raison", "A"],
    [17,116, "Red. by Full Metal Jacket", "red_fmj", "Red F", "A"],
    [17,117, "SOLID STATE SQUAD", "sssquad", "SOLID", "A"],
    [17,118, "SOLID STATE SQUAD†", "sssquadl", "SOLID†", "A"],
    [17,119, "ワルツ第17番 ト短調 大犬のワルツ", "_valse17", "大犬", "A"],
    [18,120, "Broken", "brokenrb", "Broken", "A"],
    [18,121, "Dances with Snow Fairies", "dancwith", "Dances", "A"],
    [18,122, "ELECTRIC MASSIVE DIVER", "emassive", "MASSIVE", "A"],
    [18,123, "Kailua", "kailua", "Kailua", "A"],
    [18,124, "PARADISE LOST", "paralost", "PARA LOS", "A"],
    [18,125, "perditus†paradisus", "perditus", "p†p", "A"],
    [18,126, "reunion", "reunion", "reunion", "A"],
    [18,127, "SABER WING", "saberwng", "SABER", "A"],
    [18,128, "sakura storm", "sakurast", "sakura s", "A"],
    [18,129, "Session 9-Chronicles-", "session9", "Session", "A"],
    [18,130, "SPECIAL SUMMER CAMPAIGN!", "ssc", "SSCAMP", "A"],
    [18,131, "THE BLACK KNIGHT", "tbknight", "BLACK K", "A"],
    [18,132, "ZETA～素数の世界と超越者～", "zeta", "ZETA", "A"],
    [18,133, "黒髪乱れし修羅となりて", "_krokami", "黒髪", "A"],
    [18,134, "灼熱Beach Side Bunny", "_shakunt", "灼熱", "A"],
    [18,135, "旅人リラン", "_t_rerun", "リラン", "A"],
    [19,136, "BLACK.by X-Cross Fade", "blackbyx", "BLACK X", "A"],
    [19,137, "DIAVOLO", "diavolo", "DIAVOLO", "A"],
    [19,138, "F", "f_amuro", "F", "A"],
    [19,139, "fffff", "fffff", "fffff", "A"],
    [19,140, "HAERETICUS", "haeretic", "HAERETI", "A"],
    [19,141, "Infinite cave", "inf_cave", "cave", "A"],
    [19,142, "NNRT", "nnrt", "NNRT", "A"],
    [19,143, "QUANTUM TELEPORTATION", "quantum", "TELEPO", "A"],
    [19,144, "QUANTUM TELEPORTATION†", "quantuml", "TELEPO†", "A"],
    [19,145, "quaver♪", "quaver", "quaver", "A"],
    [19,146, "Snake Stick", "snakestk", "Stick", "A"],
    [19,147, "The Limbo", "thelimbo", "Limbo", "A"],
    [19,148, "The Sampling Paradise", "t_sample", "Sampli", "A"],
    [19,149, "Todestrieb", "todestri", "Todest", "A"],
    [19,150, "WONDER WALKER", "w_walker", "WONDER", "A"],
    [19,151, "YAKSHA", "yaksha", "YAKSHA", "A"],
    [19,152, "yellow head joe", "yheadjoe", "yhj", "A"],
    [19,153, "子供の落書き帳", "_kodomo", "子供", "A"],
    [19,154, "君のハートにロックオン", "_klockon", "ロックオン", "A"],
    [19,155, "恋する☆宇宙戦争っ!!", "_koisuru", "宇宙戦争", "A"],
    [19,156, "聖人の塔", "_seijin", "聖人", "A"],
    [19,157, "天空の夜明け", "_tkyoake", "天空", "A"],
    [20,158, "Confiserie", "confiser", "Confise", "A"],
    [20,159, "DAY DREAM", "daydream", "DAY DRE", "A"],
    [20,160, "Devilz Staircase", "devilz_s", "D Stair", "A"],
    [20,161, "Elemental Creation", "elecreat", "Ele Cre", "A"],
    [20,162, "FLOWER", "flower", "FLOWER", "A"],
    [20,163, "GAIA", "gaia", "GAIA", "A"],
    [20,164, "Hollywood Galaxy", "holywood", "Holly", "A"],
    [20,165, "JOMANDA", "jomanda", "JOMANDA", "A"],
    [20,166, "Liberation", "liberatn", "Libera", "A"],
    [20,167, "Little Star", "ltl_star", "Little", "A"],
    [20,168, "neu", "neu", "neu", "A"],
    [20,169, "Plan 8", "plan8", "Plan 8", "A"],
    [20,170, "Proof of the existence", "proof_of", "Proof", "A"],
    [20,171, "rumrum triplets", "rumrum", "rumrum", "A"],
    [20,172, "Sol Cosine Job 2", "soljob2", "SCJ2", "A"],
    [20,173, "STULTI", "stulti", "STULTI", "A"],
    [20,174, "SYNC-ANTHEM", "sync_ant", "SYNC-A", "A"],
    [20,175, "Thor's Hammer", "thors_hm", "Thor's", "A"],
    [20,176, "Timepiece phase II", "tpiece_2", "Tpp", "A"],
    [20,177, "Timepiece phase II(CN Ver.)", "tpiececn", "Tpp CN", "A"],
    [20,178, "True Blue", "trueblue", "TRUE", "A"],
    [20,179, "Valanga", "valanga", "Valanga", "A"],
    [20,180, "Zirkfied", "zirkfied", "Zirk", "A"],
    [20,181, "アストライアの双皿", "_astraia", "双皿", "A"],
    [20,182, "カジノファイヤーことみちゃん", "_casino", "カジノ", "A"],
    [20,183, "龍と少女とデコヒーレンス†", "_decohel", "龍と少女†", "A"],
    [20,184, "ΕΛΠΙΣ", "_elpis", "ΕΛΠΙΣ", "A"],
    [20,185, "狂イ咲ケ焔ノ華", "_kuruizk", "狂イ咲ケ", "A"],
    [20,186, "キャトられe&恋はモ～モク", "_kyatora", "キャトられ", "A"],
    [20,187, "†渚の小悪魔ラヴリィ～レイディオ†(IIDX EDIT)", "_nagisa", "渚", "A"],
    [20,188, "音楽", "_ongaku", "音楽", "A"],
    [20,189, "シュレーディンガーの猫", "_schrcat", "猫", "A"],
    [20,190, "即席！脳直★ミュージックシステム", "_sokseki", "即席", "A"],
    [20,191, "たまゆら", "_tamayra", "たまゆら", "A"],
    [20,192, "仮想空間の旅人たち†", "_travell", "仮想空間†", "A"],
    [20,193, "トリカゴノ鳳凰", "_trikago", "トリカゴノ", "A"],
    [21,194, "Adularia", "adularia", "Adularia", "A"],
    [21,195, "Ancient Scapes", "ancients", "Ancient S", "A"],
    [21,196, "Ancient Scapes†LEGGENDARIA", "ancientl", "Ancient S†", "A"],
    [21,197, "BRAINSTORM", "brainstm", "BRAIN", "A"],
    [21,198, "Close the World feat.a☆ru", "closewld", "Close", "A"],
    [21,199, "Close the World feat.a☆ru†LEGGENDARIA", "closewdl", "Close†", "A"],
    [21,200, "DARK LEGACY", "darklgcy", "DARK ", "A"],
    [21,201, "Elektrick U-Phoria", "euphoria", "U-Phoria", "A"],
    [21,202, "Feel The Beat†LEGGENDARIA", "feelbetl", "Feel†", "A"],
    [21,203, "I will be back-オレは帰ってきた-", "iwilback", "I will", "A"],
    [21,204, "Idola", "idola", "Idora", "A"],
    [21,205, "Immortal", "immortal", "Immort", "A"],
    [21,206, "INSOMNIA", "insomnia", "INSOMNIA", "A"],
    [21,207, "invoker", "invoker", "invoker", "A"],
    [21,208, "invoker†LEGGENDARIA", "invokerl", "invoker†", "A"],
    [21,209, "KAISER PHOENIX†", "kaiserpl", "KAISER†", "A"],
    [21,210, "Last Dance", "lstdance", "Last D", "A"],
    [21,211, "PUNISHER", "punisher", "PUNISH", "A"],
    [21,212, "ra'am", "raam", "raam", "A"],
    [21,213, "rainbow guitar weeps", "rbguitar", "rgw", "A"],
    [21,214, "RIZING YOU UP", "rizingup", "RIZING", "A"],
    [21,215, "Sigmund", "sigmund", "Sigmund", "A"],
    [21,216, "Sigmund†LEGGENDARIA", "sigmundl", "Sigmund†", "A"],
    [21,217, "Unicorn tail", "unicorn", "Unicorn", "A"],
    [21,218, "Verflucht", "verflcht", "Verflu", "A"],
    [21,219, "Verflucht†LEGGENDARIA", "verflchl", "Verflu†", "A"],
    [21,220, "VOX UP", "voxup_sp", "VOX U", "A"],
    [21,221, "バンブーソード・ガール", "_bamboos", "バンブー", "A"],
    [21,222, "煉獄のエルフェリア", "_elefthe", "煉獄", "A"],
    [21,223, "疾風迅雷", "_ltspeed", "疾風", "A"],
    [21,224, "疾風迅雷†LEGGENDARIA", "_ltspedl", "疾風†", "A"],
    [21,225, "IX", "_nine_ix", "IX", "A"],
    [21,226, "旋律のドグマ～Miserables～", "_s_dogma", "ドグマ", "A"],
    [21,227, "轟け！恋のビーンボール！！", "_todorok", "轟け", "A"],
    [21,228, "廿†", "_twentyl", "廿†", "A"],
    [21,229, "海神", "_wadatmi", "海神", "A"],
    [22,230, "Beat Radiance†", "beatradl", "Beat R†", "A"],
    [22,231, "Broken Sword", "brokensw", "BroSwo", "A"],
    [22,232, "CHRONO DIVER -NORNIR-†", "chrononl", "NORNIR†", "A"],
    [22,233, "Chrono Diver -PENDULUMs-", "chrono_p", "CD PEN", "A"],
    [22,234, "cinder", "cinder", "cinder", "A"],
    [22,235, "Cosmic Cat†", "cosmical", "Cosmic†", "A"],
    [22,236, "Despair of ELFERIA", "delferia", "Despair", "A"],
    [22,237, "EBONY & IVORY", "ebnyivry", "E&I", "A"],
    [22,238, "EBONY & IVORY†", "ebnyivrl", "E&I †", "A"],
    [22,239, "entelecheia", "entelech", "entele", "A"],
    [22,240, "fallen leaves -IIDX edition-", "faleaves", "fallen", "A"],
    [22,241, "FANTASTIC THREE", "fanthree", "FANTAS", "A"],
    [22,242, "Flashes", "flashes", "Flashes", "A"],
    [22,243, "Gravigazer", "gravigzr", "Gravi", "A"],
    [22,244, "Invitation from Mr.C", "invi_mrc", "invi MrC", "A"],
    [22,245, "Night sky", "nightsky", "Night s", "A"],
    [22,246, "Rave*it!! Rave*it!!", "rave_it", "Rave*it", "A"],
    [22,247, "Reflux", "reflux", "Refulx", "A"],
    [22,248, "Say YEEEAHH", "say_yeah", "Say YE", "A"],
    [22,249, "Shooting Fireball", "shootfir", "ShootF", "A"],
    [22,250, "Sounds Of Summer", "sosummer", "S Of S", "A"],
    [22,251, "SpaceLand☆TOYBOX", "sptoybox", "S☆TOY", "A"],
    [22,252, "The Least 100sec", "t_100sec", "TL100s", "A"],
    [22,253, "TIEFSEE", "tiefsee", "TIEFSEE", "A"],
    [22,254, "TOXIC VIBRATION", "toxicvib", "TOXICV", "A"],
    [22,255, "We're so Happy(P*Light Remix) IIDX ver.", "wesoh_pl", "We're", "A"],
    [22,256, "ZZ", "zz_amuro", "ZZ", "A"],
    [22,257, "表裏一体!?怪盗いいんちょの悩みe&", "_hyouri", "怪盗", "A"],
    [22,258, "共鳴遊戯の華", "_kyoumei", "共鳴", "A"],
    [22,259, "リリーゼと炎龍レーヴァテイン", "_lilieze", "リリーゼ", "A"],
    [22,260, "夏色DIARY - L.E.D.-G STYLE MIX -", "_ntdiary", "夏色", "A"],
    [22,261, "鬼天", "_onigami", "鬼天", "A"],
    [22,262, "千年ノ理", "_sennen", "千年", "A"],
    [22,263, "少年は空を辿る", "_soratad", "少年空", "A"],
    [22,264, "それは花火のような恋", "_shanabi", "花火", "A"],
    [22,265, "超青少年ノ為ノ超多幸ナ超古典的超舞曲", "_verycls", "超青少年", "A"],
    [22,266, "超青少年ノ為ノ超多幸ナ超古典的超舞曲†", "_verycsl", "超青少年†", "A"],
    [22,267, "Ｘ↑Ｘ↓", "_x7xl", "X↑X↓", "A"],
    [23,268, "AO-1", "ao_1", "AO-1", "A"],
    [23,269, "Battle Train-IIDX Edition-", "btltrain", "BT IIDX", "A"],
    [23,270, "Blue Spring Express", "blspring", "BlueSE", "A"],
    [23,271, "chaos eater-IIDX edition-", "chaoseat", "chaos e", "A"],
    [23,272, "CODE1 revision1.0.1", "code_1", "CODE1", "A"],
    [23,273, "Devil's Gear", "dvlsgear", "Devil G", "A"],
    [23,274, "DIAMOND CROSSING", "diacross", "DIAMOND", "A"],
    [23,275, "Dynamite", "dynausao", "Dynamite", "A"],
    [23,276, "GET READY!!", "getready", "GET READY", "A"],
    [23,277, "GOBBLE", "gobblecp", "GOBBLE", "H"],
    [23,278, "Godspeed", "godspeed", "Godsp", "A"],
    [23,279, "Grand Chariot", "gchariot", "GrandC", "A"],
    [23,280, "Highcharge Divolt", "hicharge", "High D", "A"],
    [23,281, "M4K3 1T B0UNC3", "m4k3_1t", "M4K3", "A"],
    [23,282, "Nightmare before oversleep", "nightbfr", "Nbo", "A"],
    [23,283, "NINJA IS DEAD IIDX ver.", "ninja_dd", "NINJA", "A"],
    [23,284, "NZM", "nzm", "NZM", "A"],
    [23,285, "POSSESSION", "posesion", "POSSE", "A"],
    [23,286, "refrain", "refrain", "refrain", "A"],
    [23,287, "STARLIGHT DANCEHALL†", "starltdl", "STAR D†", "A"],
    [23,288, "StrayedCatz", "strycatz", "Strayed", "A"],
    [23,289, "Triple Counter", "tripleco", "TripleC", "A"],
    [23,290, "X", "x_amuro", "X", "A"],
    [23,291, "199024club -ReBounceKiller-", "199024cl", "199024", "A"],
    [23,292, "紫陽花 -AZISAI-", "_azisai", "紫陽花", "A"],
    [23,293, "駅猫のワルツ", "_ekineko", "駅猫", "A"],
    [23,294, "炸裂！イェーガー電光チョップ!!(JAEGER FINAL ATTACK)", "_jfinala", "電光チョップ", "A"],
    [23,295, "めいさいアイドル☆あいむちゃん♪", "_meisai", "めいさい", "A"],
    [23,296, "灼熱 Pt.2 Long Train Running", "_syaku_2", "灼熱 Pt.2", "A"],
    [23,297, "真 地獄超特急 -HELL or HELL-", "_sjigoku", "地獄超特急", "A"],
    [24,298, "Amazing Mirage†", "amazingl", "Amazing†", "A"],
    [24,299, "Apocalypse", "apocalrf", "Apocalypse", "A"],
    [24,300, "BabeL ～Grand Story～", "babel_gs", "BabeL", "A"],
    [24,301, "Caterpillar", "caterpil", "Caterpillar", "A"],
    [24,302, "DISAPPEAR feat. koyomin", "disapear", "DISAPPERA", "A"],
    [24,303, "DORNWALD ～Junge～", "dornwald", "DORNWALD", "A"],
    [24,304, "ECHIDNA", "echidna", "ECHIDNA", "A"],
    [24,305, "FUZIN RIZIN", "fuznrizn", "FUZIN", "A"],
    [24,306, "Go Ahead!!", "goahead", "Go Ahead", "A"],
    [24,307, "GuNGNiR", "gungnir", "GuNGNiR", "A"],
    [24,308, "HADES", "hadesmnk", "HADES", "A"],
    [24,309, "Mare Nectaris", "marenect", "Nectaris", "A"],
    [24,310, "OTENAMI Hurricane", "otenamih", "OTEMANI", "A"],
    [24,311, "Quakes", "quakes", "Quakes", "A"],
    [24,312, "RAIN", "rain", "RAIN", "A"],
    [24,313, "Rave Cannon", "rvcannon", "Rave", "A"],
    [24,314, "SEQUENCE CAT", "sequence", "SEQUENCE", "A"],
    [24,315, "Shoot'Em All", "shoot_em", "ShootEm", "A"],
    [24,316, "Sky High", "skyhigh", "Sky", "A"],
    [24,317, "Snakey Kung-fu", "snkungfu", "Snakey", "A"],
    [24,318, "Summerlights(IIDX Edition)", "summerlt", "Summer l", "A"],
    [24,319, "Super Rush", "superush", "Super", "A"],
    [24,320, "TOGAKUSHI", "togakusi", "TOGAKUSHI", "A"],
    [24,321, "刃図羅", "_buzra", "刃図羅", "A"],
    [24,322, "童話回廊", "_dowakai", "童話回廊", "A"],
    [24,323, "焔極OVERKILL", "_enkyoku", "焔極", "A"],
    [24,324, "1q影", "_hikage", "1q影", "A"],
    [24,325, "イザナミノナゲキ", "_izanami", "イザナミ", "A"],
    [24,326, "九尾狐夜行", "_kyubi", "九尾", "A"],
    [24,327, "〆", "_shime", "〆", "A"],
    [24,328, "津軽雪", "_tgryuki", "津軽行き", "A"],
    [25,329, "AA -rebuild-", "aa_rebld", "AA re", "A"],
    [25,330, "ANCHOR", "anchor", "ANCHOR", "A"],
    [25,331, "Antigravity", "antigrav", "Anti", "A"],
    [25,332, "Arca", "arca", "Arca", "A"],
    [25,333, "Boomy and The Boost", "booboost", "Boomy", "A"],
    [25,334, "DEADHEAT", "deadheat", "DEAD", "A"],
    [25,335, "DEATH†ZIGOQ～怒りの高速爆走野郎～", "dthzigoq", "DEATH", "A"],
    [25,336, "DropZ-Line-", "dropz_ln", "DropZ", "A"],
    [25,337, "Eine Haube ～聖地の果てにあるもの～", "einehaub", "Eine", "A"],
    [25,338, "EMERALDAS", "emeralds", "EMERALD", "A"],
    [25,339, "encounter", "encountr", "encounter", "A"],
    [25,340, "HYPE THE CORE", "hypecore", "HYPE", "A"],
    [25,341, "Illusionary Waterlily", "illuswtr", "Illusionary", "A"],
    [25,342, "Initiation", "initiatn", "Initiation", "A"],
    [25,343, "Life Is A Game ft.DD ナカタ Metal", "lifegame", "Life", "A"],
    [25,344, "Mira", "mira", "Mira", "A"],
    [25,345, "NITROUS CANNON", "nitrous", "NITOROUS", "A"],
    [25,346, "Papilio ulysses", "papilio", "Papilio", "A"],
    [25,347, "Persephone", "prsphone", "Persephone", "A"],
    [25,348, "Rampage", "rampage", "Rampage", "A"],
    [25,349, "Raspberry Railgun", "rrailgun", "Raspberry", "A"],
    [25,350, "Slipstream", "slipstrm", "Slip", "A"],
    [25,351, "The Chase", "thechase", "Chase", "A"],
    [25,352, "Usual Days-remix", "usualday", "Usual", "A"],
    [25,353, "VOX RUSH", "vox_rush", "VOX R", "A"],
    [25,354, "Xperanza", "xperanza", "Xperanza", "A"],
    [25,355, "255", "255_255", "255", "A"],
    [25,356, "シムルグの目醒め", "_simurgh", "シムルグ", "A"],
    [25,357, "神謳 -RESONANCE-", "_resonan", "神謳", "A"],
    [25,358, "東京神話", "_tksinwa", "東京神話", "A"],
    [26,359, "Catch Our Fire!", "catchfir", "Catch", "A"],
    [26,360, "dAuntl3ss", "dauntl3s", "dAunt3ss", "A"],
    [26,361, "Dr.Chemical & Killing Machine", "dr_chemi", "Dr.C", "A"],
    [26,362, "Drastic Dramatic", "drasticd", "Drastic", "A"],
    [26,363, "GIGA THRASH", "gigathra", "GIGA", "A"],
    [26,364, "KILL EACH OTHER", "killeach", "KILL", "A"],
    [26,365, "L.F.O", "lfo", "L.F.O", "A"],
    [26,366, "Level One", "levelone", "Lv One", "A"],
    [26,367, "LOST TECHNOLOGIE", "losttech", "LOST TEC", "A"],
    [26,368, "Painful Fate", "painfate", "Painful", "A"],
    [26,369, "Red. by Jack Trance", "red_jack", "Red J", "A"],
    [26,370, "SIGMA", "sigma", "SIGMA", "A"],
    [26,371, "THE DAY OF JUBILATIONS", "t_jubila", "JUBI", "A"],
    [26,372, "The Rebellion of Sequencer", "t_rebeli", "TRoS", "A"],
    [26,373, "Xlo", "xlo", "Xlo", "A"],
    [26,374, "金野火織の金色提言", "_k_hiori", "金色", "A"],


]
/* 
music_table = {
    //[バージョン, 曲ID, 曲名, textageID, 表示, 難易度]
    'rugged_l':[2,1, "RUGGED ASH†", "rugged_l", "RUG", "A"],
    'eranos':[3,2, "era(nostalmix)", "eranos", "era(n H", "H"],
    'eranos':[3,3, "era(nostalmix)", "eranos", "era(n A", "A"],
    'holic':[3,4, "Holic", "holic", "Holi", "A"],
    'dxy':[4,5, "DXY!", "dxy", "DXY H", "H"],
    'dxy':[4,6, "DXY!", "dxy", "DXY A", "A"],
    'erastep':[4,7, "era(step mix)", "erastep", "era(s", "A"],
    'mnmlian':[4,8, "minimalian", "mnmlian", "mini", "A"],
    'starmine':[4,9, "starmine", "starmine", "star", "A"],
    'swtlab24':[4,10, "SWEET LAB", "swtlab24", "SWEET", "A"],
    'qqq':[5,11, "QQQ", "qqq", "QQQ", "A"],
    'colors':[6,12, "Colors(radio edit)", "colors", "Colors", "A"],
    'g2':[6,13, "G2", "g2", "G2", "A"],
    'nemesis':[6,14, "NEMESIS", "nemesis", "NEME", "A"],
    'r80s_emp':[6,15, "route 80s", "r80s_emp", "80s", "A"],
    'summer':[6,16, "Summer Vacation(CU mix)", "summer", "Summ V", "A"],
    'a_amuro':[7,17, "A", "a_amuro", "A", "A"],
    'cheertra':[7,18, "Cheer Train", "cheertra", "Cheer", "A"],
    'spica':[7,19, "Spica", "spica", "Spica", "A"],
    'stoic':[7,20, "stoic", "stoic", "Stoic", "A"],
    '_kakumei':[7,21, "革命", "_kakumei", "革命H", "H"],
    '_kakumei':[7,22, "革命", "_kakumei", "革命A", "A"],
    'murmur':[8,23, "murmur twins", "murmur", "murmur", "A"],
    '_sakura':[8,24, "桜", "_sakura", "桜", "A"],
    'karma':[9,25, "Karma", "karma", "Karma", "A"],
    'loworld':[9,26, "lower world", "loworld", "lower", "A"],
    'm_child':[9,27, "moon_child", "m_child", "moon", "A"],
    'quasar':[9,28, "quasar", "quasar", "quasar", "A"],
    'rislimr':[9,29, "RISLIM-Remix-", "rislimr", "RISLIM", "A"],
    'ghost':[10,30, "GHOST REVIVAL", "ghost", "GHOST", "A"],
    'innocent':[10,31, "Innocent Walls", "innocent", "Walls", "A"],
    'loveter':[10,32, "Love Is Eternity", "loveter", "LisE", "A"],
    'no13':[10,33, "No.13", "no13", "No.13", "A"],
    'onemore':[10,34, "One More Lovely", "onemore", "OML", "A"],
    '1samurai':[10,35, "1st Samurai", "1samurai", "1st", "A"],
    '_stgekka':[10,36, "雪月花", "_stgekka", "雪月花", "A"],
    'aa_amuro':[11,37, "AA", "aa_amuro", "AA", "A"],
    'blocks':[11,38, "BLOCKS", "blocks", "BLOCKS", "A"],
    'faketime':[11,39, "FAKE TIME", "faketime", "FAKE H", "H"],
    'faketime':[11,40, "FAKE TIME", "faketime", "FAKE A", "A"],
    'genocide':[11,41, "GENOCIDE", "genocide", "GENO H", "H"],
    'genocide':[11,42, "GENOCIDE", "genocide", "GENO A", "A"],
    'gigadel':[11,43, "gigadelic", "gigadel", "giga H", "H"],
    'gigadel':[11,44, "gigadelic", "gigadel", "giga A", "A"],
    'redzonel':[11,45, "RED ZONE†", "redzonel", "RED Z", "A"],
    'sphere':[11,46, "Sphere", "sphere", "Sphere", "A"],
    'spiral_l':[11,47, "spiral galaxy†", "spiral_l", "spiral", "A"],
    '_psasori':[11,48, "ピアノ協奏曲第１番_蠍火_", "_psasori", "蠍火", "A"],
    'gardenhs':[12,49, "garden", "gardenhs", "garden", "A"],
    'inazuma':[12,50, "INAZUMA", "inazuma", "INAZUMA", "A"],
    'littlepl':[12,51, "Little Little Princess†", "littlepl", "LLP†", "A"],
    'sc_squad':[12,52, "SCREAM SQUAD", "sc_squad", "SC SQ", "A"],
    '_mei':[12,53, "冥", "_mei", "冥", "A"],
    'concert':[13,54, "Concertino in Blue", "concert", "Concer", "A"],
    'contract':[13,55, "CONTRACT", "contract", "CONTRA", "A"],
    'contracl':[13,56, "CONTRACT†", "contracl", "CONTRA†", "A"],
    'due_tmrw':[13,57, "DUE TOMORROW", "due_tmrw", "DUE", "A"],
    'ganymede':[13,58, "Ganymede", "ganymede", "Gany", "A"],
    'mint':[13,59, "MINT", "mint", "MINT", "A"],
    'trip_mc':[13,60, "tripping contact(teranoid&MC Natsack Remix)", "trip_mc", "trip", "A"],
    'waxing_l':[13,61, "waxing and wanding†", "waxing_l", "wax", "A"],
    '_kachofu':[13,62, "華蝶風雪", "_kachofu", "華蝶風雪", "A"],
    '_kagono':[13,63, "カゴノトリ～弐式～", "_kagono", "カゴ", "A"],
    '_nageki':[13,64, "嘆きの樹", "_nageki", "嘆き", "A"],
    'candygal':[14,65, "Candy Galy", "candygal", "Candy", "A"],
    'fas_maxx':[14,66, "Fascination MAXX", "fas_maxx", "FaXX", "A"],
    'inori':[14,67, "INORI", "inori", "INORI", "A"],
    'kmitachi':[14,68, "KAMAITACHI", "kmitachi", "KAMA", "A"],
    'kmitachl':[14,69, "KAMAITACHI†", "kmitachl", "KAMA †", "A"],
    'lcruster':[14,70, "LASER CRUSTER", "lcruster", "LASER", "A"],
    'op31jojo':[14,71, "op.31 叙情", "op31jojo", "op.31", "A"],
    'sens2007':[14,72, "Sense 2007", "sens2007", "SenseH", "H"],
    'sens2007':[14,73, "Sense 2007", "sens2007", "SenseA", "A"],
    'smile':[14,74, "smile", "smile", "smile", "A"],
    'snwstorm':[14,75, "snow storm", "snwstorm", "snow", "A"],
    'tranoid':[14,76, "TRANOID", "tranoid", "TRANO", "A"],
    'vanessa':[14,77, "VANESSA", "vanessa", "VANE ", "A"],
    'vanessal':[14,78, "VANESSA†", "vanessal", "VANE †", "A"],
    '_fattack':[14,79, "電人、暁に斃れる。", "_fattack", "暁", "A"],
    'anisakis':[15,80, "Anisakis-somatic mutation type Forza-", "anisakis", "Anisakis", "A"],
    'be_ok':[15,81, "Be OK", "be_ok", "BeOK", "A"],
    'bluerail':[15,82, "Blue Rain†", "bluerail", "Blue †", "A"],
    'doit_emp':[15,83, "Do it!! Do it!!", "doit_emp", "Do it", "A"],
    'fourpces':[15,84, "four pieces of heaven", "fourpces", "four", "A"],
    'icarus':[15,85, "ICARUS", "icarus", "ICA", "A"],
    'icarusl':[15,86, "ICARUS†", "icarusl", "ICA †", "A"],
    'mendes':[15,87, "MENDES", "mendes", "MENDES", "A"],
    'oratio':[15,88, "oratio", "oratio", "oratio", "A"],
    'pr_hades':[15,89, "PARANOiA ～HADES～", "pr_hades", "P HADES", "A"],
    'sa2712ac':[15,90, "satellite020712 from CODED ARMS", "sa2712ac", "sate", "A"],
    'sotart24':[15,91, "State Of The Art", "sotart24", "State", "A"],
    'tdeepstl':[15,92, "THE DEEP STRIKER†", "tdeepstl", "DEEP †", "A"],
    'troopers':[15,93, "TROOPERS", "troopers", "TROOPE", "A"],
    'ubertrel':[15,94, "Ubertreffen†", "ubertrel", "Uber†", "A"],
    '_kid_a':[15,95, "少年A", "_kid_a", "少年A", "A"],
    '_m_resid':[15,96, "ミラージュレジデンス", "_m_resid", "ミラージュ", "A"],
    'cocookie':[16,97, "Colorful Cookie", "cocookie", "Cookie", "A"],
    'gobeyond':[16,98, "Go Beyond!!", "gobeyond", "Beyond", "A"],
    'kungfu_l':[16,99, "Kung-fu Empire†", "kungfu_l", "Empire†", "A"],
    'ycodoa25':[16,100, "Y&Co. is dead or alive", "ycodoa25", "Y&Co", "A"],
    '3y3s':[16,101, "3y3s", "3y3s", "3y3s", "A"],
    '_himiko':[16,102, "卑弥呼", "_himiko", "卑弥呼", "A"],
    '_mdatn24':[16,103, "ミッドナイト堕天使", "_mdatn24", "堕天使", "A"],
    '_rintosl':[16,104, "凛として咲く花の如く†", "_rintosl", "凛†", "A"],
    'almag_ra':[17,105, "Almagest", "almag_ra", "Almag", "A"],
    'bmaniacs':[17,106, "Bad Maniacs", "bmaniacs", "Bad", "A"],
    'dominion':[17,107, "DOMINION", "dominion", "DOMI", "A"],
    'ephantom':[17,108, "eRAseRmOToRpHAntOM", "ephantom", "sRaseR", "A"],
    'evans':[17,109, "Evans", "evans", "Evans", "A"],
    'exusia':[17,110, "EXUSIA", "exusia", "EXUSIA", "A"],
    'g59':[17,111, "G59", "g59", "G59", "A"],
    'galgalim':[17,112, "GALGALIM", "galgalim", "GALGAL", "A"],
    'goldcros':[17,113, "GOLDEN CROSS", "goldcros", "GOLCRO", "A"],
    'quell':[17,114, "quell～the seventh slave～", "quell", "quell", "A"],
    'raison':[17,115, "Raison d'etre～交差する宿命～", "raison", "Raison", "A"],
    'red_fmj':[17,116, "Red. by Full Metal Jacket", "red_fmj", "Red F", "A"],
    'sssquad':[17,117, "SOLID STATE SQUAD", "sssquad", "SOLID", "A"],
    'sssquadl':[17,118, "SOLID STATE SQUAD†", "sssquadl", "SOLID†", "A"],
    '_valse17':[17,119, "ワルツ第17番 ト短調_大犬のワルツ", "_valse17", "大犬", "A"],
    'brokenrb':[18,120, "Broken", "brokenrb", "Broken", "A"],
    'dancwith':[18,121, "Dances with Snow Fairies", "dancwith", "Dances", "A"],
    'emassive':[18,122, "ELECTRIC MASSIVE DIVER", "emassive", "MASSIVE", "A"],
    'kailua':[18,123, "Kailua", "kailua", "Kailua", "A"],
    'paralost':[18,124, "PARADISE LOST", "paralost", "PARA LOS", "A"],
    'perditus':[18,125, "perditus†paradisus", "perditus", "p†p", "A"],
    'reunion':[18,126, "reunion", "reunion", "reunion", "A"],
    'saberwng':[18,127, "SABER WING", "saberwng", "SABER", "A"],
    'sakurast':[18,128, "sakura storm", "sakurast", "sakura s", "A"],
    'session9':[18,129, "Session 9-Chronicles-", "session9", "Session", "A"],
    'ssc':[18,130, "SPECIAL SUMMER CAMPAIGN!", "ssc", "SSCAMP", "A"],
    'tbknight':[18,131, "THE BLACK KNIGHT", "tbknight", "BLACK K", "A"],
    'zeta':[18,132, "ZETA～素数の世界と超越者～", "zeta", "ZETA", "A"],
    '_krokami':[18,133, "黒髪乱れし修羅となりて", "_krokami", "黒髪", "A"],
    '_shakunt':[18,134, "灼熱Beach Side Bunny", "_shakunt", "灼熱", "A"],
    '_t_rerun':[18,135, "旅人リラン", "_t_rerun", "リラン", "A"],
    'blackbyx':[19,136, "BLACK.by X-Cross Fade", "blackbyx", "BLACK X", "A"],
    'diavolo':[19,137, "DIAVOLO", "diavolo", "DIAVOLO", "A"],
    'f_amuro':[19,138, "F", "f_amuro", "F", "A"],
    'fffff':[19,139, "fffff", "fffff", "fffff", "A"],
    'haeretic':[19,140, "HAERETICUS", "haeretic", "HAERETI", "A"],
    'inf_cave':[19,141, "Infinite cave", "inf_cave", "cave", "A"],
    'nnrt':[19,142, "NNRT", "nnrt", "NNRT", "A"],
    'quantum':[19,143, "QUANTUM TELEPORTATION", "quantum", "TELEPO", "A"],
    'quantuml':[19,144, "QUANTUM TELEPORTATION†", "quantuml", "TELEPO†", "A"],
    'quaver':[19,145, "quaver♪", "quaver", "quaver", "A"],
    'snakestk':[19,146, "Snake Stick", "snakestk", "Stick", "A"],
    'thelimbo':[19,147, "The Limbo", "thelimbo", "Limbo", "A"],
    't_sample':[19,148, "The Sampling Paradise", "t_sample", "Sampli", "A"],
    'todestri':[19,149, "Todestrieb", "todestri", "Todest", "A"],
    'w_walker':[19,150, "WONDER WALKER", "w_walker", "WONDER", "A"],
    'yaksha':[19,151, "YAKSHA", "yaksha", "YAKSHA", "A"],
    'yheadjoe':[19,152, "yellow head joe", "yheadjoe", "yhj", "A"],
    '_kodomo':[19,153, "子供の落書き帳", "_kodomo", "子供", "A"],
    '_klockon':[19,154, "君のハートにロックオン", "_klockon", "ロックオン", "A"],
    '_koisuru':[19,155, "恋する☆宇宙戦争っ!!", "_koisuru", "宇宙戦争", "A"],
    '_seijin':[19,156, "聖人の塔", "_seijin", "聖人", "A"],
    '_tkyoake':[19,157, "天空の夜明け", "_tkyoake", "天空", "A"],
    'confiser':[20,158, "Confiserie", "confiser", "Confise", "A"],
    'daydream':[20,159, "DAY DREAM", "daydream", "DAY DRE", "A"],
    'devilz_s':[20,160, "Devilz Staircase", "devilz_s", "D Stair", "A"],
    'elecreat':[20,161, "Elemental Creation", "elecreat", "Ele Cre", "A"],
    'flower':[20,162, "FLOWER", "flower", "FLOWER", "A"],
    'gaia':[20,163, "GAIA", "gaia", "GAIA", "A"],
    'holywood':[20,164, "Hollywood Galaxy", "holywood", "Holly", "A"],
    'jomanda':[20,165, "JOMANDA", "jomanda", "JOMANDA", "A"],
    'liberatn':[20,166, "Liberation", "liberatn", "Libera", "A"],
    'ltl_star':[20,167, "Little Star", "ltl_star", "Little", "A"],
    'neu':[20,168, "neu", "neu", "neu", "A"],
    'plan8':[20,169, "Plan 8", "plan8", "Plan 8", "A"],
    'proof_of':[20,170, "Proof of the existence", "proof_of", "Proof", "A"],
    'rumrum':[20,171, "rumrum triplets", "rumrum", "rumrum", "A"],
    'soljob2':[20,172, "Sol Cosine Job 2", "soljob2", "SCJ2", "A"],
    'stulti':[20,173, "STULTI", "stulti", "STULTI", "A"],
    'sync_ant':[20,174, "SYNC-ANTHEM", "sync_ant", "SYNC-A", "A"],
    'thors_hm':[20,175, "Thor's Hammer", "thors_hm", "Thor's", "A"],
    'tpiece_2':[20,176, "Timepiece phase II", "tpiece_2", "Tpp", "A"],
    'tpiececn':[20,177, "Timepiece phase II(CN Ver.)", "tpiececn", "Tpp CN", "A"],
    'trueblue':[20,178, "True Blue", "trueblue", "TRUE", "A"],
    'valanga':[20,179, "Valanga", "valanga", "Valanga", "A"],
    'zirkfied':[20,180, "Zirkfied", "zirkfied", "Zirk", "A"],
    '_astraia':[20,181, "アストライアの双皿", "_astraia", "双皿", "A"],
    '_casino':[20,182, "カジノファイヤーことみちゃん", "_casino", "カジノ", "A"],
    '_decohel':[20,183, "龍と少女とデコヒーレンス†", "_decohel", "龍と少女†", "A"],
    '_elpis':[20,184, "ΕΛΠΙΣ", "_elpis", "ΕΛΠΙΣ", "A"],
    '_kuruizk':[20,185, "狂イ咲ケ焔ノ華", "_kuruizk", "狂イ咲ケ", "A"],
    '_kyatora':[20,186, "キャトられe&恋はモ～モク", "_kyatora", "キャトられ", "A"],
    '_nagisa':[20,187, "†渚の小悪魔ラヴリィ～レイディオ†(IIDX EDIT)", "_nagisa", "渚", "A"],
    '_ongaku':[20,188, "音楽", "_ongaku", "音楽", "A"],
    '_schrcat':[20,189, "シュレーディンガーの猫", "_schrcat", "猫", "A"],
    '_sokseki':[20,190, "即席！脳直★ミュージックシステム", "_sokseki", "即席", "A"],
    '_tamayra':[20,191, "たまゆら", "_tamayra", "たまゆら", "A"],
    '_travell':[20,192, "仮想空間の旅人たち†", "_travell", "仮想空間†", "A"],
    '_trikago':[20,193, "トリカゴノ鳳凰", "_trikago", "トリカゴノ", "A"],
    'adularia':[21,194, "Adularia", "adularia", "Adularia", "A"],
    'ancients':[21,195, "Ancient Scapes", "ancients", "Ancient S", "A"],
    'ancientl':[21,196, "Ancient Scapes†LEGGENDARIA", "ancientl", "Ancient S†", "A"],
    'brainstm':[21,197, "BRAINSTORM", "brainstm", "BRAIN", "A"],
    'closewld':[21,198, "Close the World feat.a☆ru", "closewld", "Close", "A"],
    'closewdl':[21,199, "Close the World feat.a☆ru†LEGGENDARIA", "closewdl", "Close†", "A"],
    'darklgcy':[21,200, "DARK LEGACY", "darklgcy", "DARK ", "A"],
    'euphoria':[21,201, "Elektrick U-Phoria", "euphoria", "U-Phoria", "A"],
    'feelbetl':[21,202, "Feel The Beat†LEGGENDARIA", "feelbetl", "Feel†", "A"],
    'iwilback':[21,203, "I will be back-オレは帰ってきた-", "iwilback", "I will", "A"],
    'idola':[21,204, "Idola", "idola", "Idora", "A"],
    'immortal':[21,205, "Immortal", "immortal", "Immort", "A"],
    'insomnia':[21,206, "INSOMNIA", "insomnia", "INSOMNIA", "A"],
    'invoker':[21,207, "invoker", "invoker", "invoker", "A"],
    'invokerl':[21,208, "invoker†LEGGENDARIA", "invokerl", "invoker†", "A"],
    'kaiserpl':[21,209, "KAISER PHOENIX†", "kaiserpl", "KAISER†", "A"],
    'lstdance':[21,210, "Last Dance", "lstdance", "Last D", "A"],
    'punisher':[21,211, "PUNISHER", "punisher", "PUNISH", "A"],
    'raam':[21,212, "ra'am", "raam", "raam", "A"],
    'rbguitar':[21,213, "rainbow guitar weeps", "rbguitar", "rgw", "A"],
    'rizingup':[21,214, "RIZING YOU UP", "rizingup", "RIZING", "A"],
    'sigmund':[21,215, "Sigmund", "sigmund", "Sigmund", "A"],
    'sigmundl':[21,216, "Sigmund†LEGGENDARIA", "sigmundl", "Sigmund†", "A"],
    'unicorn':[21,217, "Unicorn tail", "unicorn", "Unicorn", "A"],
    'verflcht':[21,218, "Verflucht", "verflcht", "Verflu", "A"],
    'verflchl':[21,219, "Verflucht†LEGGENDARIA", "verflchl", "Verflu†", "A"],
    'voxup_sp':[21,220, "VOX UP", "voxup_sp", "VOX U", "A"],
    '_bamboos':[21,221, "バンブーソード・ガール", "_bamboos", "バンブー", "A"],
    '_elefthe':[21,222, "煉獄のエルフェリア", "_elefthe", "煉獄", "A"],
    '_ltspeed':[21,223, "疾風迅雷", "_ltspeed", "疾風", "A"],
    '_ltspedl':[21,224, "疾風迅雷†LEGGENDARIA", "_ltspedl", "疾風†", "A"],
    '_nine_ix':[21,225, "IX", "_nine_ix", "IX", "A"],
    '_s_dogma':[21,226, "旋律のドグマ～Miserables～", "_s_dogma", "ドグマ", "A"],
    '_todorok':[21,227, "轟け！恋のビーンボール！！", "_todorok", "轟け", "A"],
    '_twentyl':[21,228, "廿†", "_twentyl", "廿†", "A"],
    '_wadatmi':[21,229, "海神", "_wadatmi", "海神", "A"],
    'beatradl':[22,230, "Beat Radiance†", "beatradl", "Beat R†", "A"],
    'brokensw':[22,231, "Broken Sword", "brokensw", "BroSwo", "A"],
    'chrononl':[22,232, "CHRONO DIVER -NORNIR-†", "chrononl", "NORNIR†", "A"],
    'chrono_p':[22,233, "Chrono Diver -PENDULUMs-", "chrono_p", "CD PEN", "A"],
    'cinder':[22,234, "cinder", "cinder", "cinder", "A"],
    'cosmical':[22,235, "Cosmic Cat†", "cosmical", "Cosmic†", "A"],
    'delferia':[22,236, "Despair of ELFERIA", "delferia", "Despair", "A"],
    'ebnyivry':[22,237, "EBONY & IVORY", "ebnyivry", "E&I", "A"],
    'ebnyivrl':[22,238, "EBONY & IVORY†", "ebnyivrl", "E&I †", "A"],
    'entelech':[22,239, "entelecheia", "entelech", "entele", "A"],
    'faleaves':[22,240, "fallen leaves -IIDX edition-", "faleaves", "fallen", "A"],
    'fanthree':[22,241, "FANTASTIC THREE", "fanthree", "FANTAS", "A"],
    'flashes':[22,242, "Flashes", "flashes", "Flashes", "A"],
    'gravigzr':[22,243, "Gravigazer", "gravigzr", "Gravi", "A"],
    'invi_mrc':[22,244, "Invitation from Mr.C", "invi_mrc", "invi MrC", "A"],
    'nightsky':[22,245, "Night sky", "nightsky", "Night s", "A"],
    'rave_it':[22,246, "Rave*it!! Rave*it!!", "rave_it", "Rave*it", "A"],
    'reflux':[22,247, "Reflux", "reflux", "Refulx", "A"],
    'say_yeah':[22,248, "Say YEEEAHH", "say_yeah", "Say YE", "A"],
    'shootfir':[22,249, "Shooting Fireball", "shootfir", "ShootF", "A"],
    'sosummer':[22,250, "Sounds Of Summer", "sosummer", "S Of S", "A"],
    'sptoybox':[22,251, "SpaceLand☆TOYBOX", "sptoybox", "S☆TOY", "A"],
    't_100sec':[22,252, "The Least 100sec", "t_100sec", "TL100s", "A"],
    'tiefsee':[22,253, "TIEFSEE", "tiefsee", "TIEFSEE", "A"],
    'toxicvib':[22,254, "TOXIC VIBRATION", "toxicvib", "TOXICV", "A"],
    'wesoh_pl':[22,255, "We're so Happy(P*Light Remix) IIDX ver.", "wesoh_pl", "We're", "A"],
    'zz_amuro':[22,256, "ZZ", "zz_amuro", "ZZ", "A"],
    '_hyouri':[22,257, "表裏一体!?怪盗いいんちょの悩みe&", "_hyouri", "怪盗", "A"],
    '_kyoumei':[22,258, "共鳴遊戯の華", "_kyoumei", "共鳴", "A"],
    '_lilieze':[22,259, "リリーゼと炎龍レーヴァテイン", "_lilieze", "リリーゼ", "A"],
    '_ntdiary':[22,260, "夏色DIARY - L.E.D.-G STYLE MIX -", "_ntdiary", "夏色", "A"],
    '_onigami':[22,261, "鬼天", "_onigami", "鬼天", "A"],
    '_sennen':[22,262, "千年ノ理", "_sennen", "千年", "A"],
    '_soratad':[22,263, "少年は空を辿る", "_soratad", "少年空", "A"],
    '_shanabi':[22,264, "それは花火のような恋", "_shanabi", "花火", "A"],
    '_verycls':[22,265, "超青少年ノ為ノ超多幸ナ超古典的超舞曲", "_verycls", "超青少年", "A"],
    '_verycsl':[22,266, "超青少年ノ為ノ超多幸ナ超古典的超舞曲†", "_verycsl", "超青少年†", "A"],
    '_x7xl':[22,267, "Ｘ↑Ｘ↓", "_x7xl", "X↑X↓", "A"],
    'ao_1':[23,268, "AO-1", "ao_1", "AO-1", "A"],
    'btltrain':[23,269, "Battle Train-IIDX Edition-", "btltrain", "BT IIDX", "A"],
    'blspring':[23,270, "Blue Spring Express", "blspring", "BlueSE", "A"],
    'chaoseat':[23,271, "chaos eater-IIDX edition-", "chaoseat", "chaos e", "A"],
    'code_1':[23,272, "CODE:1 revision1.0.1", "code_1", "CODE:1", "A"],
    'dvlsgear':[23,273, "Devil's Gear", "dvlsgear", "Devil G", "A"],
    'diacross':[23,274, "DIAMOND CROSSING", "diacross", "DIAMOND", "A"],
    'dynausao':[23,275, "Dynamite", "dynausao", "Dynamite", "A"],
    'getready':[23,276, "GET READY!!", "getready", "GET READY", "A"],
    'gobblecp':[23,277, "GOBBLE", "gobblecp", "GOBBLE", "H"],
    'godspeed':[23,278, "Godspeed", "godspeed", "Godsp", "A"],
    'gchariot':[23,279, "Grand Chariot", "gchariot", "GrandC", "A"],
    'hicharge':[23,280, "Highcharge Divolt", "hicharge", "High D", "A"],
    'm4k3_1t':[23,281, "M4K3 1T B0UNC3", "m4k3_1t", "M4K3", "A"],
    'nightbfr':[23,282, "Nightmare before oversleep", "nightbfr", "Nbo", "A"],
    'ninja_dd':[23,283, "NINJA IS DEAD IIDX ver.", "ninja_dd", "NINJA", "A"],
    'nzm':[23,284, "NZM", "nzm", "NZM", "A"],
    'posesion':[23,285, "POSSESSION", "posesion", "POSSE", "A"],
    'refrain':[23,286, "refrain", "refrain", "refrain", "A"],
    'starltdl':[23,287, "STARLIGHT DANCEHALL†", "starltdl", "STAR D†", "A"],
    'strycatz':[23,288, "StrayedCatz", "strycatz", "Strayed", "A"],
    'tripleco':[23,289, "Triple Counter", "tripleco", "TripleC", "A"],
    'x_amuro':[23,290, "X", "x_amuro", "X", "A"],
    '199024cl':[23,291, "199024club -Re:BounceKiller-", "199024cl", "199024", "A"],
    '_azisai':[23,292, "紫陽花 -AZISAI-", "_azisai", "紫陽花", "A"],
    '_ekineko':[23,293, "駅猫のワルツ", "_ekineko", "駅猫", "A"],
    '_jfinala':[23,294, "炸裂！イェーガー電光チョップ!!(JAEGER FINAL ATTACK)", "_jfinala", "電光チョップ", "A"],
    '_meisai':[23,295, "めいさいアイドル☆あいむちゃん♪", "_meisai", "めいさい", "A"],
    '_syaku_2':[23,296, "灼熱 Pt.2 Long Train Running", "_syaku_2", "灼熱 Pt.2", "A"],
    '_sjigoku':[23,297, "真 地獄超特急 -HELL or HELL-", "_sjigoku", "地獄超特急", "A"],
    'amazingl':[24,298, "Amazing Mirage†", "amazingl", "Amazing†", "A"],
    'apocalrf':[24,299, "Apocalypse", "apocalrf", "Apocalypse", "A"],
    'babel_gs':[24,300, "BabeL ～Grand Story～", "babel_gs", "BabeL", "A"],
    'caterpil':[24,301, "Caterpillar", "caterpil", "Caterpillar", "A"],
    'disapear':[24,302, "DISAPPEAR feat. koyomin", "disapear", "DISAPPERA", "A"],
    'dornwald':[24,303, "DORNWALD ～Junge～", "dornwald", "DORNWALD", "A"],
    'echidna':[24,304, "ECHIDNA", "echidna", "ECHIDNA", "A"],
    'fuznrizn':[24,305, "FUZIN RIZIN", "fuznrizn", "FUZIN", "A"],
    'goahead':[24,306, "Go Ahead!!", "goahead", "Go Ahead", "A"],
    'gungnir':[24,307, "GuNGNiR", "gungnir", "GuNGNiR", "A"],
    'hadesmnk':[24,308, "HADES", "hadesmnk", "HADES", "A"],
    'marenect':[24,309, "Mare Nectaris", "marenect", "Nectaris", "A"],
    'otenamih':[24,310, "OTENAMI Hurricane", "otenamih", "OTEMANI", "A"],
    'quakes':[24,311, "Quakes", "quakes", "Quakes", "A"],
    'rain':[24,312, "RAIN", "rain", "RAIN", "A"],
    'rvcannon':[24,313, "Rave Cannon", "rvcannon", "Rave", "A"],
    'sequence':[24,314, "SEQUENCE CAT", "sequence", "SEQUENCE", "A"],
    'shoot_em':[24,315, "Shoot'Em All", "shoot_em", "ShootEm", "A"],
    'skyhigh':[24,316, "Sky High", "skyhigh", "Sky", "A"],
    'snkungfu':[24,317, "Snakey Kung-fu", "snkungfu", "Snakey", "A"],
    'summerlt':[24,318, "Summerlights(IIDX Edition)", "summerlt", "Summer l", "A"],
    'superush':[24,319, "Super Rush", "superush", "Super", "A"],
    'togakusi':[24,320, "TOGAKUSHI", "togakusi", "TOGAKUSHI", "A"],
    '_buzra':[24,321, "刃図羅", "_buzra", "刃図羅", "A"],
    '_dowakai':[24,322, "童話回廊", "_dowakai", "童話回廊", "A"],
    '_enkyoku':[24,323, "焔極OVERKILL", "_enkyoku", "焔極", "A"],
    '_hikage':[24,324, "1q影", "_hikage", "1q影", "A"],
    '_izanami':[24,325, "イザナミノナゲキ", "_izanami", "イザナミ", "A"],
    '_kyubi':[24,326, "九尾狐夜行", "_kyubi", "九尾", "A"],
    '_shime':[24,327, "〆", "_shime", "〆", "A"],
    '_tgryuki':[24,328, "津軽雪", "_tgryuki", "津軽行き", "A"],
    'aa_rebld':[25,329, "AA -rebuild-", "aa_rebld", "AA re", "A"],
    'anchor':[25,330, "ANCHOR", "anchor", "ANCHOR", "A"],
    'antigrav':[25,331, "Antigravity", "antigrav", "Anti", "A"],
    'arca':[25,332, "Arca", "arca", "Arca", "A"],
    'booboost':[25,333, "Boomy and The Boost", "booboost", "Boomy", "A"],
    'deadheat':[25,334, "DEADHEAT", "deadheat", "DEAD", "A"],
    'dthzigoq':[25,335, "DEATH†ZIGOQ～怒りの高速爆走野郎～", "dthzigoq", "DEATH", "A"],
    'dropz_ln':[25,336, "DropZ-Line-", "dropz_ln", "DropZ", "A"],
    'einehaub':[25,337, "Eine Haube ～聖地の果てにあるもの～", "einehaub", "Eine", "A"],
    'emeralds':[25,338, "EMERALDAS", "emeralds", "EMERALD", "A"],
    'encountr':[25,339, "encounter", "encountr", "encounter", "A"],
    'hypecore':[25,340, "HYPE THE CORE", "hypecore", "HYPE", "A"],
    'illuswtr':[25,341, "Illusionary Waterlily", "illuswtr", "Illusionary", "A"],
    'initiatn':[25,342, "Initiation", "initiatn", "Initiation", "A"],
    'lifegame':[25,343, "Life Is A Game ft.DD_ナカタ_Metal", "lifegame", "Life", "A"],
    'mira':[25,344, "Mira", "mira", "Mira", "A"],
    'nitrous':[25,345, "NITROUS CANNON", "nitrous", "NITOROUS", "A"],
    'papilio':[25,346, "Papilio ulysses", "papilio", "Papilio", "A"],
    'prsphone':[25,347, "Persephone", "prsphone", "Persephone", "A"],
    'rampage':[25,348, "Rampage", "rampage", "Rampage", "A"],
    'rrailgun':[25,349, "Raspberry Railgun", "rrailgun", "Raspberry", "A"],
    'slipstrm':[25,350, "Slipstream", "slipstrm", "Slip", "A"],
    'thechase':[25,351, "The Chase", "thechase", "Chase", "A"],
    'usualday':[25,352, "Usual Days-remix", "usualday", "Usual", "A"],
    'vox_rush':[25,353, "VOX RUSH", "vox_rush", "VOX R", "A"],
    'xperanza':[25,354, "Xperanza", "xperanza", "Xperanza", "A"],
    '255_255':[25,355, "255", "255_255", "255", "A"],
    '_simurgh':[25,356, "シムルグの目醒め", "_simurgh", "シムルグ", "A"],
    '_resonan':[25,357, "神謳 -RESONANCE-", "_resonan", "神謳", "A"],
    '_tksinwa':[25,358, "東京神話", "_tksinwa", "東京神話", "A"],
    'catchfir':[26,359, "Catch Our Fire!", "catchfir", "Catch", "A"],
    'dauntl3s':[26,360, "dAuntl3ss", "dauntl3s", "dAunt3ss", "A"],
    'dr_chemi':[26,361, "Dr.Chemical & Killing Machine", "dr_chemi", "Dr.C", "A"],
    'drasticd':[26,362, "Drastic Dramatic", "drasticd", "Drastic", "A"],
    'gigathra':[26,363, "GIGA THRASH", "gigathra", "GIGA", "A"],
    'killeach':[26,364, "KILL EACH OTHER", "killeach", "KILL", "A"],
    'lfo':[26,365, "L.F.O", "lfo", "L.F.O", "A"],
    'levelone':[26,366, "Level One", "levelone", "Lv One", "A"],
    'losttech':[26,367, "LOST TECHNOLOGIE", "losttech", "LOST TEC", "A"],
    'painfate':[26,368, "Painful Fate", "painfate", "Painful", "A"],
    'red_jack':[26,369, "Red. by Jack Trance", "red_jack", "Red J", "A"],
    'sigma':[26,370, "SIGMA", "sigma", "SIGMA", "A"],
    't_jubila':[26,371, "THE DAY OF JUBILATIONS", "t_jubila", "JUBI", "A"],
    't_rebeli':[26,372, "The Rebellion of Sequencer", "t_rebeli", "TRoS", "A"],
    'xlo':[26,373, "Xlo", "xlo", "Xlo", "A"],
    '_k_hiori':[26,374, "金野火織の金色提言", "_k_hiori", "金色", "A"]
} */
